---
title: "Lab_7"
output: 
  html_document:
    df_print: paged
---


```{r, echo=FALSE}
#limpando o documento html final
knitr::opts_chunk$set(echo=FALSE,error=FALSE,warning=FALSE,message=FALSE)
```

```{r}
library(haven)
library(tidyverse)
library(knitr)
library(stargazer)
library(broom)
library(jtools)
library(interactions)
library(interflex)
library(coefplot)
#opening do file

clinton_termometer <- read_stata("nes1996_modif.dta")
#clinton_termometer
```

```{r}
clinton_termometer %>%
  summarise(mean(hillary, na.rm=T),
            mean(wmnmvt, na.rm=T),
            mean(faminc,na.rm=T),
            sd(hillary, na.rm=T),
            sd(wmnmvt, na.rm=T),
            sd(faminc, na.rm=T)) %>%
  kable()

#kernel density wwmnmvt
ggplot(clinton_termometer, aes(wmnmvt)) +
  geom_density() +
  ggtitle("wmnmvt Kernel's density estimate")

#kernel denisty faminc

ggplot(clinton_termometer, aes(faminc)) +
  geom_density() +
    ggtitle("faminc Kernel's density estimate")

```

```{r}
#creating 2 dummy variables for feminism and high income
#I use the 50th percentile as a cut 
clinton_termometer <-
clinton_termometer %>%
  mutate("feminist"=case_when(wmnmvt >= 63 ~ 1,
                              wmnmvt < 63 ~ 0),
         "high_income"= case_when(faminc >= 20 ~ 1,
                                  faminc < 20 ~0
                                  ))
```

```{r, results='asis'}
#estimating an additive regression model based on the variables created above

#additive model.when we consider the casual factors to have the same effect always (we add the effects and we came up with the predicted value)

#multicplicative model including interactions
additive_model <- clinton_termometer %>%
lm(hillary ~feminist + high_income, data = .) %>%
  stargazer(type="html", title = "Additive Regression Model with Feminism and High Income",
            single.row = T,
            keep.stat = c("n"))

additive_model

add_model_graph <-  clinton_termometer %>%
lm(hillary ~feminist + high_income, data = .)%>%
  tidy()

add_model_graph %>%
  mutate(conf.lo=estimate-1.96*std.error,
         conf.hi=estimate+1.96*std.error) %>%
  filter(term!="(Intercept)") %>%
  ggplot() +
  geom_point(aes(x=term,y=estimate))+
  geom_errorbar(aes(x=term,y=estimate,ymin=conf.lo,ymax=conf.hi), width=0.1)+
  geom_hline(yintercept=0,lty=2)+
  theme_minimal()

model_1 <-
clinton_termometer %>%
lm(hillary ~feminist + high_income, data = .)

#coefplot
coefplot(model = model_1) 

#scatterplot

clinton_termometer %>%
  ggplot() +
  geom_point(aes(x = feminist,
                 y = hillary)) +
  geom_smooth(aes(x = feminist,
                 y = hillary), 
              method = "lm") +
  ggtitle("Scatter plot Feminism")


clinton_termometer %>%
  ggplot() +
  geom_point(aes(x = high_income,
                 y = hillary)) +
  geom_smooth(aes(x = high_income,
                 y = hillary), method = "lm") +
  ggtitle("Scatter plot Income")
```

```{r}
#estimating an interaction regression model based on the dummies
interacion_model <- clinton_termometer %>%
    lm(hillary ~feminist*high_income,data = . )

interacion_model
```

```{r}
interact_plot(interacion_model, pred = "feminist",modx="high_income", interval = TRUE )
```

```{r}
#part 2
```




